/**
 * 都道府県別 住民税情報
 *
 * AUTO-GENERATED by scripts/build-prefecture-info.js
 * 元データ: data/jumin-specs/*.js
 * 生成日時: 2026-04-30
 *
 * 超過課税あり: 37都道府県
 * 超過課税なし: 10都道府県
 *
 * description.full（超過課税あり県）は手動補完が必要です。
 * 再生成: node scripts/build-prefecture-info.js
 */

export const PREFECTURE_INFO = {
  "aichi": {
    "name": "愛知県",
    "prefRate": 0.04,
    "prefPerCapita": 1500,
    "surcharge": {
      "perCapita": 500
    },
    "taxName": "あいち森と緑づくり税",
    "sourceUrl": "https://www.pref.aichi.jp/zeimu/shotoku/midori.html",
    "description": {
      "short": "均等割+500円（あいち森と緑づくり税）",
      "full": "愛知県では「あいち森と緑づくり税」として、個人県民税の均等割に500円が上乗せされています。2008年度から実施されており、荒廃した人工林の間伐・再造林と里山整備に充てられています。"
    }
  },
  "akita": {
    "name": "秋田県",
    "prefRate": 0.04,
    "prefPerCapita": 1800,
    "surcharge": {
      "perCapita": 800
    },
    "taxName": "水と緑の森づくり税",
    "sourceUrl": "https://www.pref.akita.lg.jp/pages/archive/3973",
    "description": {
      "short": "均等割+800円（水と緑の森づくり税）",
      "full": "秋田県では「水と緑の森づくり税」として、個人県民税の均等割に800円が上乗せされています。2008年度から実施されており、森林整備（間伐・育林）と水源かん養機能の維持向上に充てられています。"
    }
  },
  "aomori": {
    "name": "青森県",
    "prefRate": 0.04,
    "prefPerCapita": 1000,
    "surcharge": null,
    "taxName": null,
    "sourceUrl": "https://www.pref.aomori.lg.jp/soshiki/zaimu/zeimu/003_01koken.html",
    "description": {
      "short": "超過課税なし（標準税率）",
      "full": "青森県では個人県民税の超過課税はありません。地方税法の標準税率（所得割4%、均等割1,000円）が適用されています。"
    }
  },
  "chiba": {
    "name": "千葉県",
    "prefRate": 0.04,
    "prefPerCapita": 1000,
    "surcharge": null,
    "taxName": null,
    "sourceUrl": "https://www.pref.chiba.lg.jp/zeimu/aramashi/shurui/kojin-kenminzei/",
    "description": {
      "short": "超過課税なし（標準税率）",
      "full": "千葉県では個人県民税の超過課税はありません。地方税法の標準税率（所得割4%、均等割1,000円）が適用されています。"
    }
  },
  "ehime": {
    "name": "愛媛県",
    "prefRate": 0.04,
    "prefPerCapita": 1700,
    "surcharge": {
      "perCapita": 700
    },
    "taxName": "森林環境税",
    "sourceUrl": "https://www.pref.ehime.jp/page/1629.html",
    "description": {
      "short": "均等割+700円（森林環境税）",
      "full": "愛媛県では「森林環境税」として、個人県民税の均等割に700円が上乗せされています。2005年度から実施されており、間伐・再造林など人工林整備と県民参加の森林保全活動に充てられています。"
    }
  },
  "fukui": {
    "name": "福井県",
    "prefRate": 0.04,
    "prefPerCapita": 1000,
    "surcharge": null,
    "taxName": null,
    "sourceUrl": "https://www.pref.fukui.lg.jp/doc/zeimu/type/kojinkenmin.html",
    "description": {
      "short": "超過課税なし（標準税率）",
      "full": "福井県では個人県民税の超過課税はありません。地方税法の標準税率（所得割4%、均等割1,000円）が適用されています。"
    }
  },
  "fukuoka": {
    "name": "福岡県",
    "prefRate": 0.04,
    "prefPerCapita": 1500,
    "surcharge": {
      "perCapita": 500
    },
    "taxName": "福岡県森林環境税",
    "sourceUrl": "https://www.city.kitakyushu.lg.jp/contents/08801107.html",
    "description": {
      "short": "均等割+500円（福岡県森林環境税）",
      "full": "福岡県では「福岡県森林環境税」として、個人県民税の均等割に500円が上乗せされています。2007年度から実施されており、人工林の間伐・再造林と水源かん養機能の維持向上に充てられています。"
    }
  },
  "fukushima": {
    "name": "福島県",
    "prefRate": 0.04,
    "prefPerCapita": 2000,
    "surcharge": {
      "perCapita": 1000
    },
    "taxName": "ふくしま森林づくり県民税",
    "sourceUrl": "https://www.pref.fukushima.lg.jp/sec/01115d/zeimu22.html",
    "description": {
      "short": "均等割+1,000円（ふくしま森林づくり県民税）",
      "full": "福島県では「ふくしま森林づくり県民税」として、個人県民税の均等割に1,000円が上乗せされています。2006年度から実施されており、荒廃した人工林の間伐・再造林と森林環境の保全整備に充てられています。"
    }
  },
  "gifu": {
    "name": "岐阜県",
    "prefRate": 0.04,
    "prefPerCapita": 2000,
    "surcharge": {
      "perCapita": 1000
    },
    "taxName": "清流の国ぎふ森林・環境税",
    "sourceUrl": "https://www.pref.gifu.lg.jp/page/8460.html",
    "description": {
      "short": "均等割+1,000円（清流の国ぎふ森林・環境税）",
      "full": "岐阜県では「清流の国ぎふ森林・環境税」として、個人県民税の均等割に1,000円が上乗せされています。2007年度から実施されており、間伐・再造林など森林整備と清流・自然環境の保全に充てられています。"
    }
  },
  "gunma": {
    "name": "群馬県",
    "prefRate": 0.04,
    "prefPerCapita": 1700,
    "surcharge": {
      "perCapita": 700
    },
    "taxName": "ぐんま緑の県民税",
    "sourceUrl": "https://www.pref.gunma.jp/page/7190.html",
    "description": {
      "short": "均等割+700円（ぐんま緑の県民税）",
      "full": "群馬県では「ぐんま緑の県民税」として、個人県民税の均等割に700円が上乗せされています。2014年度から実施されており、人工林の間伐・整備と里山林の保全活動に充てられています。"
    }
  },
  "hiroshima": {
    "name": "広島県",
    "prefRate": 0.04,
    "prefPerCapita": 1500,
    "surcharge": {
      "perCapita": 500
    },
    "taxName": "ひろしまの森づくり県民税",
    "sourceUrl": "https://www.pref.hiroshima.lg.jp/site/zei/1172044970276.html",
    "description": {
      "short": "均等割+500円（ひろしまの森づくり県民税）",
      "full": "広島県では「ひろしまの森づくり県民税」として、個人県民税の均等割に500円が上乗せされています。2007年度から実施されており、人工林の間伐・再造林と水源かん養・土砂災害防止など森林の公益的機能の維持向上に充てられています。"
    }
  },
  "hokkaido": {
    "name": "北海道",
    "prefRate": 0.04,
    "prefPerCapita": 1000,
    "surcharge": null,
    "taxName": null,
    "sourceUrl": "https://www.pref.hokkaido.lg.jp/sm/zim/tax/kozin_d02.html",
    "description": {
      "short": "超過課税なし（標準税率）",
      "full": "北海道では個人県民税の超過課税はありません。地方税法の標準税率（所得割4%、均等割1,000円）が適用されています。"
    }
  },
  "hyogo": {
    "name": "兵庫県",
    "prefRate": 0.04,
    "prefPerCapita": 1800,
    "surcharge": {
      "perCapita": 800
    },
    "taxName": "兵庫県民緑税",
    "sourceUrl": "https://www.city.kobe.lg.jp/a83576/kurashi/tax/shikenminze/keisan/index.html",
    "description": {
      "short": "均等割+800円（兵庫県民緑税）",
      "full": "兵庫県では「兵庫県民緑税」として、個人県民税の均等割に800円が上乗せされています。2006年度から実施されており、森林整備（間伐・再造林）と里山・水源林の保全活動に充てられています。"
    }
  },
  "ibaraki": {
    "name": "茨城県",
    "prefRate": 0.04,
    "prefPerCapita": 2000,
    "surcharge": {
      "perCapita": 1000
    },
    "taxName": "森林湖沼環境税",
    "sourceUrl": "https://www.pref.ibaraki.jp/nourinsuisan/rinsei/shinkozei/tax/gaiyou/index.html",
    "description": {
      "short": "均等割+1,000円（森林湖沼環境税）",
      "full": "茨城県では「森林湖沼環境税」として、個人県民税の均等割に1,000円が上乗せされています。2006年度から実施されており、森林整備と霞ヶ浦をはじめとする湖沼の水質保全に充てられています。"
    }
  },
  "ishikawa": {
    "name": "石川県",
    "prefRate": 0.04,
    "prefPerCapita": 1500,
    "surcharge": {
      "perCapita": 500
    },
    "taxName": "いしかわ森林環境税",
    "sourceUrl": "https://www.pref.ishikawa.lg.jp/shinrin/kikaku/kankyouzei/index.html",
    "description": {
      "short": "均等割+500円（いしかわ森林環境税）",
      "full": "石川県では「いしかわ森林環境税」として、個人県民税の均等割に500円が上乗せされています。2007年度から実施されており、人工林の強度間伐による混交林化など森林の公益的機能の回復に充てられています。"
    }
  },
  "iwate": {
    "name": "岩手県",
    "prefRate": 0.04,
    "prefPerCapita": 2000,
    "surcharge": {
      "perCapita": 1000
    },
    "taxName": "いわての森林づくり県民税",
    "sourceUrl": "https://www.pref.iwate.jp/kensei/zei/gaiyou/kojin/1073136.html",
    "description": {
      "short": "均等割+1,000円（いわての森林づくり県民税）",
      "full": "岩手県では「いわての森林づくり県民税」として、個人県民税の均等割に1,000円が上乗せされています。2007年度から実施されており、人工林の間伐・再造林と森林の公益的機能の維持向上に充てられています。"
    }
  },
  "kagawa": {
    "name": "香川県",
    "prefRate": 0.04,
    "prefPerCapita": 1000,
    "surcharge": null,
    "taxName": null,
    "sourceUrl": "https://www.pref.kagawa.lg.jp/zeimu/zeikin/shiori.html",
    "description": {
      "short": "超過課税なし（標準税率）",
      "full": "香川県では個人県民税の超過課税はありません。地方税法の標準税率（所得割4%、均等割1,000円）が適用されています。"
    }
  },
  "kagoshima": {
    "name": "鹿児島県",
    "prefRate": 0.04,
    "prefPerCapita": 1500,
    "surcharge": {
      "perCapita": 500
    },
    "taxName": "みんなの森づくり県民税",
    "sourceUrl": "https://www.pref.kagoshima.jp/ab07/kurashi-kankyo/zei/shinzei/shinrin/sinrin.html",
    "description": {
      "short": "均等割+500円（みんなの森づくり県民税）",
      "full": "鹿児島県では「みんなの森づくり県民税」として、個人県民税の均等割に500円が上乗せされています。2005年度から実施されており、荒廃した人工林の再造林支援と里山の保全整備に充てられています。"
    }
  },
  "kanagawa": {
    "name": "神奈川県",
    "prefRate": 0.04025,
    "prefPerCapita": 1300,
    "surcharge": {
      "perCapita": 300,
      "rate": 0.00025
    },
    "taxName": "神奈川県水源環境保全税",
    "sourceUrl": "https://www.city.yokohama.lg.jp/kurashi/koseki-zei-hoken/zeikin/y-shizei/kojin-shiminzei-kenminzei/kojin-shimin.html",
    "description": {
      "short": "均等割+300円（神奈川県水源環境保全税）・所得割+0.025%",
      "full": "神奈川県では「神奈川県水源環境保全税」として、個人県民税に超過課税が上乗せされています。所得割は標準4%に+0.025%、均等割は標準1,000円に+300円が加算されます。2007年度から実施されており、水源地域の森林・河川・湧水地の整備保全に充てられています。"
    }
  },
  "kochi": {
    "name": "高知県",
    "prefRate": 0.04,
    "prefPerCapita": 1500,
    "surcharge": {
      "perCapita": 500
    },
    "taxName": "高知県森林環境税",
    "sourceUrl": "https://www.pref.kochi.lg.jp/doc/ken-kankyouzei/",
    "description": {
      "short": "均等割+500円（高知県森林環境税）",
      "full": "高知県では「高知県森林環境税」として、個人県民税の均等割に500円が上乗せされています。2003年度から実施されており、人工林の間伐・再造林と県民参加の森林保全活動（全国初の県独自森林環境税）に充てられています。"
    }
  },
  "kumamoto": {
    "name": "熊本県",
    "prefRate": 0.04,
    "prefPerCapita": 1500,
    "surcharge": {
      "perCapita": 500
    },
    "taxName": "水とみどりの森づくり税",
    "sourceUrl": "https://www.city.kumamoto.jp/kiji00312986/index.html",
    "description": {
      "short": "均等割+500円（水とみどりの森づくり税）",
      "full": "熊本県では「水とみどりの森づくり税」として、個人県民税の均等割に500円が上乗せされています。2006年度から実施されており、荒廃した人工林の間伐・再造林と水源かん養機能の維持向上に充てられています。"
    }
  },
  "kyoto": {
    "name": "京都府",
    "prefRate": 0.04,
    "prefPerCapita": 1600,
    "surcharge": {
      "perCapita": 600
    },
    "taxName": "豊かな森を育てる府民税",
    "sourceUrl": "https://www.city.kyoto.lg.jp/gyozai/page/0000028299.html",
    "description": {
      "short": "均等割+600円（豊かな森を育てる府民税）",
      "full": "京都府では「豊かな森を育てる府民税」として、個人府民税の均等割に600円が上乗せされています。2006年度から実施されており、人工林の間伐・再造林と府民参加の里山保全活動に充てられています。"
    }
  },
  "mie": {
    "name": "三重県",
    "prefRate": 0.04,
    "prefPerCapita": 2000,
    "surcharge": {
      "perCapita": 1000
    },
    "taxName": "みえ森と緑の県民税",
    "sourceUrl": "https://www.pref.mie.lg.jp/ZEIMU/HP/80013017950.htm",
    "description": {
      "short": "均等割+1,000円（みえ森と緑の県民税）",
      "full": "三重県では「みえ森と緑の県民税」として、個人県民税の均等割に1,000円が上乗せされています。2014年度から実施されており、間伐・再造林など森林整備と県民参加による森林保全活動に充てられています。"
    }
  },
  "miyagi": {
    "name": "宮城県",
    "prefRate": 0.04,
    "prefPerCapita": 2200,
    "surcharge": {
      "perCapita": 1200
    },
    "taxName": "みやぎ環境税",
    "sourceUrl": "https://www.city.sendai.jp/shiminze-kikaku/kurashi/tetsuzuki/zekin/kojin/gaiyo.html",
    "description": {
      "short": "均等割+1,200円（みやぎ環境税）",
      "full": "宮城県では「みやぎ環境税」として、個人県民税の均等割に1,200円が上乗せされています。2011年度から実施されており、自然環境の保全整備および森林・里山の整備に充てられています。"
    }
  },
  "miyazaki": {
    "name": "宮崎県",
    "prefRate": 0.04,
    "prefPerCapita": 1500,
    "surcharge": {
      "perCapita": 500
    },
    "taxName": "みやざき森林環境税",
    "sourceUrl": "https://www.pref.miyazaki.lg.jp/miyazaki-morizukuri/kurashi/shizen/20200513095941.html",
    "description": {
      "short": "均等割+500円（みやざき森林環境税）",
      "full": "宮崎県では「みやざき森林環境税」として、個人県民税の均等割に500円が上乗せされています。2006年度から実施されており、花粉の少ないスギ苗木の普及支援と人工林の再造林・間伐整備に充てられています。"
    }
  },
  "nagano": {
    "name": "長野県",
    "prefRate": 0.04,
    "prefPerCapita": 1500,
    "surcharge": {
      "perCapita": 500
    },
    "taxName": "長野県森林づくり県民税",
    "sourceUrl": "https://www.pref.nagano.lg.jp/rinsei/sangyo/ringyo/shisaku/kenminze/kenminzei.html",
    "description": {
      "short": "均等割+500円（長野県森林づくり県民税）",
      "full": "長野県では「長野県森林づくり県民税」として、個人県民税の均等割に500円が上乗せされています。2008年度から実施されており、人工林の間伐・再造林と森林整備による水源かん養機能の維持向上に充てられています。"
    }
  },
  "nagasaki": {
    "name": "長崎県",
    "prefRate": 0.04,
    "prefPerCapita": 1500,
    "surcharge": {
      "perCapita": 500
    },
    "taxName": "ながさき森林環境税",
    "sourceUrl": "https://www.pref.nagasaki.jp/bunrui/shigoto-sangyo/shinrin-ringyo/kankyouzei/",
    "description": {
      "short": "均等割+500円（ながさき森林環境税）",
      "full": "長崎県では「ながさき森林環境税」として、個人県民税の均等割に500円が上乗せされています。2007年度から実施されており、人工林の間伐・整備と水源かん養・土砂災害防止など森林の公益的機能の保全に充てられています。"
    }
  },
  "nara": {
    "name": "奈良県",
    "prefRate": 0.04,
    "prefPerCapita": 1500,
    "surcharge": {
      "perCapita": 500
    },
    "taxName": "奈良県森林環境税",
    "sourceUrl": "https://www.pref.nara.jp/12162.htm",
    "description": {
      "short": "均等割+500円（奈良県森林環境税）",
      "full": "奈良県では「奈良県森林環境税」として、個人県民税の均等割に500円が上乗せされています。2006年度から実施されており、人工林の間伐・再造林と水源かん養・生物多様性の維持向上に充てられています。"
    }
  },
  "niigata": {
    "name": "新潟県",
    "prefRate": 0.04,
    "prefPerCapita": 1000,
    "surcharge": null,
    "taxName": null,
    "sourceUrl": "https://www.pref.niigata.lg.jp/sec/zeimu/kkenmin.html",
    "description": {
      "short": "超過課税なし（標準税率）",
      "full": "新潟県では個人県民税の超過課税はありません。地方税法の標準税率（所得割4%、均等割1,000円）が適用されています。"
    }
  },
  "oita": {
    "name": "大分県",
    "prefRate": 0.04,
    "prefPerCapita": 1500,
    "surcharge": {
      "perCapita": 500
    },
    "taxName": "大分県森林環境税",
    "sourceUrl": "https://www.pref.oita.jp/soshiki/16210/sinrinkankyouzei.html",
    "description": {
      "short": "均等割+500円（大分県森林環境税）",
      "full": "大分県では「大分県森林環境税」として、個人県民税の均等割に500円が上乗せされています。2006年度から実施されており、人工林の間伐・再造林と水源かん養機能の維持向上に充てられています。"
    }
  },
  "okayama": {
    "name": "岡山県",
    "prefRate": 0.04,
    "prefPerCapita": 1500,
    "surcharge": {
      "perCapita": 500
    },
    "taxName": "おかやま森づくり県民税",
    "sourceUrl": "https://www.pref.okayama.jp/page/360893.html",
    "description": {
      "short": "均等割+500円（おかやま森づくり県民税）",
      "full": "岡山県では「おかやま森づくり県民税」として、個人県民税の均等割に500円が上乗せされています。2004年度から実施されており、荒廃した人工林の間伐・再造林と水源かん養機能の維持向上に充てられています。"
    }
  },
  "okinawa": {
    "name": "沖縄県",
    "prefRate": 0.04,
    "prefPerCapita": 1000,
    "surcharge": null,
    "taxName": null,
    "sourceUrl": "https://www.pref.okinawa.lg.jp/kurashikankyo/zeikin/1003660/index.html",
    "description": {
      "short": "超過課税なし（標準税率）",
      "full": "沖縄県では個人県民税の超過課税はありません。地方税法の標準税率（所得割4%、均等割1,000円）が適用されています。"
    }
  },
  "osaka": {
    "name": "大阪府",
    "prefRate": 0.04,
    "prefPerCapita": 1300,
    "surcharge": {
      "perCapita": 300
    },
    "taxName": "大阪府森林環境税",
    "sourceUrl": "https://www.city.osaka.lg.jp/zaisei/page/0000383147.html",
    "description": {
      "short": "均等割+300円（大阪府森林環境税）",
      "full": "大阪府では「大阪府森林環境税」として、個人府民税の均等割に300円が上乗せされています。2016年度から実施されており、森林整備による土砂流出・流木発生防止など府民の生命・財産を守る防災対策に充てられています。"
    }
  },
  "saga": {
    "name": "佐賀県",
    "prefRate": 0.04,
    "prefPerCapita": 1500,
    "surcharge": {
      "perCapita": 500
    },
    "taxName": "佐賀県森林環境税",
    "sourceUrl": "https://www.pref.saga.lg.jp/kiji00332041/index.html",
    "description": {
      "short": "均等割+500円（佐賀県森林環境税）",
      "full": "佐賀県では「佐賀県森林環境税」として、個人県民税の均等割に500円が上乗せされています。2008年度から実施されており、人工林の間伐・再造林と県民参加の森林保全活動に充てられています。"
    }
  },
  "saitama": {
    "name": "埼玉県",
    "prefRate": 0.04,
    "prefPerCapita": 1000,
    "surcharge": null,
    "taxName": null,
    "sourceUrl": "https://www.pref.saitama.lg.jp/a0209/z-kurashiindex/z-2-1.html",
    "description": {
      "short": "超過課税なし（標準税率）",
      "full": "埼玉県では個人県民税の超過課税はありません。地方税法の標準税率（所得割4%、均等割1,000円）が適用されています。"
    }
  },
  "shiga": {
    "name": "滋賀県",
    "prefRate": 0.04,
    "prefPerCapita": 1800,
    "surcharge": {
      "perCapita": 800
    },
    "taxName": "琵琶湖森林づくり県民税",
    "sourceUrl": "https://www.pref.shiga.lg.jp/ippan/kurashi/zeikin/20003.html",
    "description": {
      "short": "均等割+800円（琵琶湖森林づくり県民税）",
      "full": "滋賀県では「琵琶湖森林づくり県民税」として、個人県民税の均等割に800円が上乗せされています。2006年度から実施されており、琵琶湖の水源を担う森林の間伐・再造林と公益的機能の維持向上に充てられています。"
    }
  },
  "shimane": {
    "name": "島根県",
    "prefRate": 0.04,
    "prefPerCapita": 1500,
    "surcharge": {
      "perCapita": 500
    },
    "taxName": "島根県水と緑の森づくり税",
    "sourceUrl": "https://www.pref.shimane.lg.jp/life/zei/ken/syurui/mizuto/mizuto.html",
    "description": {
      "short": "均等割+500円（島根県水と緑の森づくり税）",
      "full": "島根県では「島根県水と緑の森づくり税」として、個人県民税の均等割に500円が上乗せされています。2005年度から実施されており、人工林の間伐・再造林と水源かん養・山地災害防止など森林の公益的機能の維持向上に充てられています。"
    }
  },
  "shizuoka": {
    "name": "静岡県",
    "prefRate": 0.04,
    "prefPerCapita": 1400,
    "surcharge": {
      "perCapita": 400
    },
    "taxName": "静岡県森林づくり県民税",
    "sourceUrl": "https://www.city.hamamatsu.shizuoka.jp/shiminze/zei/siminze/kintou.html",
    "description": {
      "short": "均等割+400円（静岡県森林づくり県民税）",
      "full": "静岡県では「静岡県森林づくり県民税」として、個人県民税の均等割に400円が上乗せされています。2007年度から実施されており、人工林の間伐・再造林と水源かん養機能の維持向上に充てられています。"
    }
  },
  "tochigi": {
    "name": "栃木県",
    "prefRate": 0.04,
    "prefPerCapita": 1700,
    "surcharge": {
      "perCapita": 700
    },
    "taxName": "とちぎの元気な森づくり県民税",
    "sourceUrl": "https://www.pref.tochigi.lg.jp/b07/life/zeikin/zeikin/mori.html",
    "description": {
      "short": "均等割+700円（とちぎの元気な森づくり県民税）",
      "full": "栃木県では「とちぎの元気な森づくり県民税」として、個人県民税の均等割に700円が上乗せされています。2008年度から実施されており、人工林の間伐・再造林と里山林整備による森林の公益的機能の維持向上に充てられています。"
    }
  },
  "tokushima": {
    "name": "徳島県",
    "prefRate": 0.04,
    "prefPerCapita": 1000,
    "surcharge": null,
    "taxName": null,
    "sourceUrl": "https://www.pref.tokushima.lg.jp/FAQ/docs/00003513/",
    "description": {
      "short": "超過課税なし（標準税率）",
      "full": "徳島県では個人県民税の超過課税はありません。地方税法の標準税率（所得割4%、均等割1,000円）が適用されています。"
    }
  },
  "tokyo": {
    "name": "東京都",
    "prefRate": 0.04,
    "prefPerCapita": 1000,
    "surcharge": null,
    "taxName": null,
    "sourceUrl": "https://www.tax.metro.tokyo.lg.jp/kazei/life/kojin_ju",
    "description": {
      "short": "超過課税なし（標準税率）",
      "full": "東京都では個人都民税の超過課税はありません。地方税法の標準税率（所得割4%、均等割1,000円）が適用されています。"
    }
  },
  "tottori": {
    "name": "鳥取県",
    "prefRate": 0.04,
    "prefPerCapita": 1500,
    "surcharge": {
      "perCapita": 500
    },
    "taxName": "鳥取県豊かな森づくり協働税",
    "sourceUrl": "https://www.pref.tottori.lg.jp/309149.htm",
    "description": {
      "short": "均等割+500円（鳥取県豊かな森づくり協働税）",
      "full": "鳥取県では「鳥取県豊かな森づくり協働税」として、個人県民税の均等割に500円が上乗せされています。2023年度から実施されており、市民と行政が協働する里山・人工林の整備（前身の「森林環境保全税」は2005年度から実施）に充てられています。"
    }
  },
  "toyama": {
    "name": "富山県",
    "prefRate": 0.04,
    "prefPerCapita": 1500,
    "surcharge": {
      "perCapita": 500
    },
    "taxName": "富山県水と緑の森づくり税",
    "sourceUrl": "https://www.pref.toyama.jp/1107/kurashi/seikatsu/zeikin/kenzei/m01-00/m01-01.html",
    "description": {
      "short": "均等割+500円（富山県水と緑の森づくり税）",
      "full": "富山県では「富山県水と緑の森づくり税」として、個人県民税の均等割に500円が上乗せされています。2007年度から実施されており、水と緑の豊かな森林の整備と水源かん養機能の維持向上に充てられています。"
    }
  },
  "wakayama": {
    "name": "和歌山県",
    "prefRate": 0.04,
    "prefPerCapita": 1500,
    "surcharge": {
      "perCapita": 500
    },
    "taxName": "和歌山県紀の国森づくり税",
    "sourceUrl": "https://www.pref.wakayama.lg.jp/prefg/010500/kenzei/moridukuri/moridukuri.html",
    "description": {
      "short": "均等割+500円（和歌山県紀の国森づくり税）",
      "full": "和歌山県では「和歌山県紀の国森づくり税」として、個人県民税の均等割に500円が上乗せされています。2007年度から実施されており、人工林の間伐・再造林と紀伊半島の水源林・里山保全に充てられています。"
    }
  },
  "yamagata": {
    "name": "山形県",
    "prefRate": 0.04,
    "prefPerCapita": 2000,
    "surcharge": {
      "perCapita": 1000
    },
    "taxName": "やまがた緑環境税",
    "sourceUrl": "https://www.pref.yamagata.jp/020007/zei_shitsumon/midori/midori.html",
    "description": {
      "short": "均等割+1,000円（やまがた緑環境税）",
      "full": "山形県では「やまがた緑環境税」として、個人県民税の均等割に1,000円が上乗せされています。2007年度から実施されており、荒廃した人工林の間伐・再造林と里山・水源林の整備保全に充てられています。"
    }
  },
  "yamaguchi": {
    "name": "山口県",
    "prefRate": 0.04,
    "prefPerCapita": 1500,
    "surcharge": {
      "perCapita": 500
    },
    "taxName": "やまぐち森林づくり県民税",
    "sourceUrl": "https://www.pref.yamaguchi.lg.jp/soshiki/5/12482.html",
    "description": {
      "short": "均等割+500円（やまぐち森林づくり県民税）",
      "full": "山口県では「やまぐち森林づくり県民税」として、個人県民税の均等割に500円が上乗せされています。2005年度から実施されており、放置人工林の間伐・竹林整備と水源かん養・山地災害防止など森林の公益的機能の回復に充てられています。"
    }
  },
  "yamanashi": {
    "name": "山梨県",
    "prefRate": 0.04,
    "prefPerCapita": 1500,
    "surcharge": {
      "perCapita": 500
    },
    "taxName": "山梨県森林環境税",
    "sourceUrl": "https://www.pref.yamanashi.jp/zeimu/shinrinkankyouzei.html",
    "description": {
      "short": "均等割+500円（山梨県森林環境税）",
      "full": "山梨県では「山梨県森林環境税」として、個人県民税の均等割に500円が上乗せされています。2012年度から実施されており、荒廃した人工林の間伐・再造林と富士山をはじめとする水源林の保全に充てられています。"
    }
  }
};

// Node.js 環境向け
if (typeof module !== 'undefined') module.exports = { PREFECTURE_INFO };
